import{S as m,N as v,A as h,i as f}from"./assets/vendor-e7c3b180.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const c={menuText:document.querySelector(".header-menu-text"),menuList:document.querySelector(".header-menu-list"),btnMob:document.querySelector(".header-btn-mob"),headerBackdrop:document.querySelector(".header-backdrop"),headerModalClose:document.querySelector(".header-modal-menu-close"),headerModalMenu:document.querySelector(".header-modal-menu")};c.menuText.addEventListener("click",w);function w(){c.menuList.classList.contains("is-open")?c.menuList.classList.remove("is-open"):c.menuList.classList.add("is-open")}c.btnMob.addEventListener("click",y);c.headerModalMenu.addEventListener("click",g);function y(){c.headerBackdrop.classList.add("is-open")}function g(l){l.target.nodeName!=="DIV"&&c.headerBackdrop.classList.remove("is-open")}document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".ac-trigger").forEach(n=>{n.addEventListener("click",function(){const o=this.closest(".faq-item"),i=o.querySelector(".ac-panel"),e=o.querySelector(".icon-answer use");o.classList.contains("is-active")?(o.classList.remove("is-active"),i.style.height="0",e.setAttribute("href","../img/symbol-defs.svg#icon-down")):(o.classList.add("is-active"),i.style.height=i.scrollHeight+"px",e.setAttribute("href","../img/symbol-defs.svg#icon-up"))})})});const u=document.querySelector(".reviews-section");if(u){let e=function(r){return r.map(a=>`
    <li class="reviews-card swiper-slide">
        <img class="reviews-card-img" src="${a.avatar_url}" alt="${a.author}'s avatar">
        <div class="reviews-card-data">
          <h3 class="reviews-card-name">${a.author}</h3>
          <p class="review-text">${a.review}</p>
        </div>
      </li>
  `).join("")};const l=u.querySelector(".reviews-cards"),n=u.querySelector(".reviews-btn-prev"),o=u.querySelector(".reviews-btn-next");async function i(){const p="https://portfolio-js.b.goit.study/api"+"/reviews";try{const s=await fetch(p);if(!s.ok)throw new Error(`HTTP error! status: ${s.status}`);const d=await s.json();return console.log("Fetched data:",d),d}catch(s){return console.error("Fetch error:",s),f.error({position:"topRight",message:"Not Found"}),[]}}async function t(){try{const r=await i();if(r.length>0){const a=e(r);l.insertAdjacentHTML("beforeend",a);const p=new m(u.querySelector(".swiper"),{modules:[v,h],breakpoints:{320:{slidesPerView:1,loop:!1},768:{slidesPerView:2,spaceBetween:16,loop:!1},1440:{slidesPerView:4,spaceBetween:16,loop:!1}},autoplay:{delay:3e3,disableOnInteraction:!0,pauseOnMouseEnter:!0},keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0},navigation:{nextEl:".reviews-btn-next",prevEl:".reviews-btn-prev"}});document.addEventListener("keydown",s=>{if(s.key==="ArrowRight")p.slideNext();else if(s.key==="ArrowLeft")p.slidePrev();else if(s.key==="Tab"){const d=document.activeElement;d===n?(s.preventDefault(),o.focus()):d===o&&(s.preventDefault(),n.focus())}})}else console.log("No reviews to display")}catch(r){console.error("Render error:",r),f.error({position:"topRight",message:"Failed to load reviews"})}}t()}new m(".projects-swiper-container",{slidesPerView:3,spaceBetween:30,freeMode:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});
//# sourceMappingURL=commonHelpers.js.map
